[build]
  # No build command needed for static sites
  command = ""
  
  # Specify the directory to deploy (root directory in this case)
  publish = "."

[build.environment]
  # Skip any build process
  NODE_ENV = "production"

# Configure redirects for single page application behavior if needed
[[redirects]]
  from = "/quem-somos/*"
  to = "/quem-somos/index.html"
  status = 200

# Handle 404 errors
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
